# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dvnaQpUdN6-z_V6ORgdtQSOU68GvmchV
"""

x = '*'  # right triangle
l= int(input('number or rows for the triangle: '))
triangle =[l*x,(l-1)*x,(l-2)*x,(l-3)*x,(l-4)*x,(l-5)*x,(l-6)*x,(l-7)*x,(l-8)*x,(l-9)*x]
if l>10:
  print('sorry but a triangle of more than ten rows cannot be shown on this screen')
elif l<=10 and l>=2:
  for y in triangle:
    print(y)
else:
  print('lines are insufficient to form a triangle')

x = '*'  #right triangle reversed
l= int(input('number or rows for the triangle: '))
triangle =[l*x,(l-1)*x,(l-2)*x,(l-3)*x,(l-4)*x,(l-5)*x,(l-6)*x,(l-7)*x,(l-8)*x,(l-9)*x]
if l>10:
  print('sorry but a triangle of more than ten rows cannot be shown on this screen')
elif l<=10 and l>=2:
  for y in reversed(triangle):
    print(y)
else:
  print('lines are insufficient to form a triangle')

